### ISSUE TITLE
在实例 WS2812_WIFI中的rgbkey

### ISSUE THREAD

**Issue by haohaostudio** [blinker-iot/blinker-library#525]
在实例 WS2812_WIFI中的rgbkey没有在文档中找到详细说明，谷歌后也没有找到答案，希望你们可以抽出一点点时间回答一下了，谢谢，开发辛苦了

**Comment by i3water** [comment]
https://diandeng.tech/doc/arduino-support

#### BlinkerRGB  
颜色组件, 用于读取/设置RGB及亮度值  

**函数** :
- attach()  
    *BlinkerRGB.attach()*  
    设置颜色组件的回调函数, 当收到指令时会调用该回调函数
- brightness()  
    *BlinkerRGB.brightness()*  
    设置颜色组件的亮度值
- print()  
    *BlinkerRGB.print()*  
    发送用户需要的RGB数值及亮度值到APP  
    *BlinkerRGB.print(R, G, B)*  
    发送RGB及前一次设置的亮度值  
    *BlinkerRGB.print(R, G, B, Brightness)*  
    发送RGB及亮度值

初始化, 创建对象
```cpp
#define RGB_1 "RGBKey"

BlinkerRGB RGB1(RGB_1);
```
用于处理 **RGB** 收到数据的回调函数
```cpp
void rgb1_callback(uint8_t r_value, uint8_t g_value, 
                    uint8_t b_value, uint8_t bright_value)
{
    digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
    BLINKER_LOG("R value: ", r_value);
    BLINKER_LOG("G value: ", g_value);
    BLINKER_LOG("B value: ", b_value);
    BLINKER_LOG("Rrightness value: ", bright_value);
}
```

在 **setup()** 中注册回调函数
```cpp
RGB1.attach(rgb1_callback);
```
> *也可以在创建对象时注册回调函数:
>> BlinkerRGB RGB1(RGB_1, rgb1_callback);
