### ISSUE TITLE
CORRUPT HEAP

### ISSUE THREAD

**Issue by UPUPGOO** [blinker-iot/blinker-library#533]
非常感谢你们提供的这套解决方案，使用方式也非常简便。
但我在ESP32上使用Blinker.print的时候，发生了错误，ESP32重启。

> CORRUPT HEAP: Bad head at 0x3ffe09a4. Expected 0xabba1234 got 0x3ffe0c1c
assertion "head != NULL" failed: file "/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap_poisoning.c", line 214, function: multi_heap_free
abort() was called at PC 0x400eba9b on core 1
Backtrace: 0x40091470:0x3ffdf8f0 0x400916a1:0x3ffdf910 0x400eba9b:0x3ffdf930 0x400910e5:0x3ffdf960 0x40084b26:0x3ffdf980 0x400850e1:0x3ffdf9a0 0x4000bec7:0x3ffdf9c0 0x400d276b:0x3ffdf9e0 0x400d54d7:0x3ffdfa00 0x400d554a:0x3ffdfa30 0x4008e089:0x3ffdfa50
Rebooting...

当我注释掉Blinker.print时候，一切正常。所以我觉得函数里面一定发生了什么，使得堆栈溢出。
您能帮助我一下吗？以下是我的代码：想转发一下串口过来的数据到调试窗口(monitor)里面。
串口数据是这样的格式：

> freq:123
step:100
length:10
...

> void setup()
{
  Serial.begin(115200);
  controlSerial.begin(115200);
#ifdef BLINKER_PRINT
  BLINKER_DEBUG.stream(BLINKER_PRINT);
#endif
  Blinker.begin();
  BLINKER_TAST_INIT();
}
void loop()
{
  if (Serial.available() > 0)
  {
    String line = "";
    while (Serial.available() > 0)
    {
      line += char(controlSerial.read());
      Blinker.delay(2);
    }
    if (line.length() > 0)
    {
      BLINKER_LOG(line);
      Blinker.print(line);
    }
  }
  Blinker.delay(50);
}

代码和软件都是最新的。

**Comment by i3water** [comment]
----------------------------- 删除下面的内容 -----------------------------  
提问指南  
=============
请按如下说明描述您的问题，以便您的问题能够得到解决。  

1. 对照下方的 基本信息 表，在[]中填入x。  
2. 对照下发的 设备信息 表，在[]中填入您的设备信息。
3. 检查是否使用最新的库及APP，因为这个问题可能在最新的版本中已修复。
4. 描述您的问题。
5. 如果有设备端串口LOG信息，请提供LOG信息(建议DEBUG ALL下查看LOG信息)。
6. 一个能正常运行的描述您问题的最小示例代码。不要提供您的整个项目代码。
7. 如果编译报错，请提供完整的报错信息。
8. 如果使用串口蓝牙模块或者blinker AT固件, 请提供接线电路示意。
9. 提交您的问题前请将该提问指南删除。

----------------------------- 删除上面的内容 -----------------------------  

== 提问请到论坛 https://www.arduino.cn/forum-132-1.html ==

## 基本信息
- [] 这个问题满足提问指南
- [] 我阅读了开发文档
- [] 我使用了最新的库及APP进行测试，但是问题仍然存在
- [] 我搜索过类似问题的解决方法但是仍然无法解决
- [] 有设备端的LOG信息
- [] 有编译报错信息
- [] 我已填写基本信息

## 设备信息
- 硬件: [ESP-12|wifiduino|Arduino UNO]
- 接入方式: [BLE|WIFI]
- package版本: [esp8266-arduino-2.5.0dev|esp32-1.0.1-rc3]
- blinker库版本: [arduino 0.3.0|py 0.2.0]
- 开发环境: [Arduino|linux]
- 操作系统: [Windows|Ubuntu|MacOS]

## IDE 中的设置
- Module: [Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Mode: [qio|dio|other]
- Flash Size: [4MB/1MB]
- lwip Variant: [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method: [ck|nodemcu]
- Flash Frequency: [40Mhz]
- CPU Frequency: [80Mhz|160MHz]
- Upload Using: [OTA|SERIAL]
- Upload Speed: [115200|other] (serial upload only)
## 手机信息及APP信息
- 手机品牌及型号  
- android系统版本（请注意是android系统版本，不是厂商自己的版本号）
- blinker App版本  

## 问题描述
在这里填写您的问题

## 代码
在这里填写您出现问题的最小示例代码

## LOG信息
在这里填写您设备串口输出的LOG信息

## 编译信息
在这里填写您IDE编译报错信息
