### ISSUE TITLE
SMARTCONFIG配网问题

### ISSUE THREAD

**Issue by MaK-er1** [blinker-iot/blinker-library#563]
## 设备信息
- 硬件: [ESP-12|wifiduino|
- 接入方式: |WIFI]
- package版本: [esp8266-arduino-2.5.0dev|
- blinker库版本: [arduino 0.3.0|
- 开发环境: [Arduino|
- 操作系统: [Windows|

## IDE 中的设置
- Module:|Nodemcu|
- Flash Mode: |dio|
- Flash Size: [4MB/
- lwip Variant: [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method: [ck|nodemcu]
- Flash Frequency: [40Mhz]
- CPU Frequency: [80Mhz|160MHz]
- Upload Using: [OTA|SERIAL]
- Upload Speed: [115200|other] (serial upload only)

## 问题描述
占用EEPROM地址，导致SMARTCONFIG配网失败，有什么办法可以改变该地址

## LOG信息
Blinker Timer loaded!
Warning!EEPROM address 1536-2431 is used for Blinker Timer!
DON'T USE THESE EEPROM ADDRESS!

**Comment by i3water** [comment]
这只是个提示信息，告知用户使用EEPROM时避开这部分地址，并不会导致配网失败。
