### ISSUE TITLE
MIOT例子中如下代码中AliGenie Query outlet的意思是？

### ISSUE THREAD

**Issue by molun** [blinker-iot/blinker-library#569]
void miotQuery(int32_t queryCode, uint8_t num)
{
    BLINKER_LOG("AliGenie Query outlet: ", num,", codes: ", queryCode);

**Comment by heavenla** [comment]
反馈给服务器及app，天猫精灵请求的是那个插座或者开关，请求代码是ON或者OFF之类的

**Comment by i3water** [comment]
忘记改了，应该是MIOT Query outlet，大意是服务器要查询排插上第几个开关的状态。
