### ISSUE TITLE
如果修改类型为 multi_outlet 的设备单独给插座命名

### ISSUE THREAD

**Issue by 851248662** [blinker-iot/blinker-library#585]
![6912747067affb4b79bd7dba092e758](https://user-images.githubusercontent.com/61673908/143665984-da97e25a-1c0c-4baf-98af-52d4733b4467.jpg)

如何单独给插孔命名
我修改设备名称只能修改前两个字

**Comment by coloz** [comment]
非点灯方面原因，小爱那边不支持修改。可以使用小爱app训练功能修改语音指令。
