### ISSUE TITLE
esp8266 mqtt 示例代码能不能提供一个订阅的 例子

### ISSUE THREAD

**Issue by blinker123** [blinker-iot/blinker-library#589]
已经有了 发布的代码，求一个订阅的代码 ，我不会写。

这是发布消息，可以正常编译使用
  if (BLINKER_PROTOCOL_MQTT != NULL) {
        String pub_topic = "/device/" + Blinker.deviceName() + "/s";
        String pub_data = "{\"toDevice\":\"the device name you need pub to\",\"data\":{\"hello\":\"blinker\"}}";
        BLINKER_PROTOCOL_MQTT->publish(pub_topic.c_str(), pub_data.c_str());
    } 

增加 一个订阅，编译能过，不知道怎么注册回调方法

        BLINKER_PROTOCOL_MQTT->subscribeTopic(pub_topic.c_str());

**Comment by coloz** [comment]
blinker lib使用Adafruit_MQTT_Library实现MQTT通信，您可以通过该库例程，了解用法https://github.com/adafruit/Adafruit_MQTT_Library/tree/master/examples
