### ISSUE TITLE
安信可ESP-12H无法通过编译

### ISSUE THREAD

**Issue by pdtopdog** [blinker-iot/blinker-library#592]
## 设备信息
- 硬件: ESP-12H
- 接入方式: WIFI
- package版本: esp32-2.0.4
- blinker库版本: arduino 0.4.0
- 开发环境: Arduino
- 操作系统: Windows

## IDE 中的设置
- Module:ESP32S2 DEV
- Flash Mode: DIO
- Flash Size: 4M
- Flash Frequency: 80Mhz
- CPU Frequency: 240MHz
- Upload Using: SERIAL
- Upload Speed: 115200
## 手机信息及APP信息
- 手机品牌及型号  
- android系统版本（请注意是android系统版本，不是厂商自己的版本号）
- blinker App版本  

## 问题描述
不能编译

## 代码
#define BLINKER_WIFI
#define BLINKER_WIDGET

#include <Blinker.h>

const int led = 9;
char auth[] = "******";
char ssid[] = "ssid";
char pswd[] = "password";

BlinkerWiFi                 Blinker(WiFiESP);
// 新建组件对象
BlinkerButton<BlinkerWiFi>  Button1(Blinker, "btn-abc");
BlinkerNumber<BlinkerWiFi>  Number1(Blinker, "num-abc");

int counter = 0;

// 按下按键即会执行该函数
void button1_callback(const String & state)
{
    BLINKER_LOG("get button state: ", state);
    digitalWrite(led, !digitalRead(led));
}

// 如果未绑定的组件被触发，则会执行其中内容
void dataRead(const String & data)
{
    BLINKER_LOG("Blinker readString: ", data);
    counter++;
    Number1.print(counter);
}

void setup()
{
    // 初始化串口
    Serial.begin(115200);
    BLINKER_DEBUG.stream(Serial);
    BLINKER_DEBUG.debugAll();
    
    // 初始化有LED的IO
    pinMode(led, OUTPUT);
    digitalWrite(led, HIGH);
    // 初始化blinker
    Blinker.begin(auth, ssid, pswd);
    Blinker.attachData(dataRead);

    Button1.attach(button1_callback);
}

void loop()
{
    Blinker.run();
}

## LOG信息
无信息

## 编译信息
\blinker-library-dev_4.0\src/Blinker/BlinkerProtocol.h:261:64: error: 'class EspClass' has no member named 'getCoreVersion'; did you mean 'getSdkVersion'?
     BLINKER_LOG(TAG_PROTO, BLINKER_F("package version: "), ESP.getCoreVersion());
                                                                ^~~~~~~~~~~~~~
                                                                getSdkVersion
exit status 1

**Comment by coloz** [comment]
请使用最新的dev4.0配合esp32 package 2.0.5测试
