### ISSUE TITLE
合宙ESP32C3使用小爱同学的例程编译报错'class EspClass' has no member named 'getCoreVersion'; did you mean 'getSdkVersion'?

### ISSUE THREAD

**Issue by ybyllc** [blinker-iot/blinker-library#594]
## 基本信息
- [] 这个问题满足提问指南
- [] 我阅读了开发文档
- [] 我使用了最新的库及APP进行测试，但是问题仍然存在
- [] 我搜索过类似问题的解决方法但是仍然无法解决
- [] 有设备端的LOG信息
- [] 有编译报错信息
- [] 我已填写基本信息

## 设备信息
- 硬件: [ESP-32C3]
- 接入方式: [WIFI]
- package版本: [esp8266-arduino-2.5.0dev|esp32-1.0.1-rc3]
- blinker库版本: [arduino 0.4.0beta]
- 开发环境: [Arduino]
- 操作系统: [Windows]

## 问题描述
编译报错

## 代码

```
#define BLINKER_WIFI
#define BLINKER_WIDGET
#define BLINKER_MIOT_OUTLET

#include <Blinker.h>

char auth[] = "";
char ssid[] = "";
char pswd[] = "";

BlinkerWiFi                 Blinker(WiFiESP);
BLINKERMIOT<BlinkerWiFi>    BlinkerMIOT(Blinker);

bool oState = false;

void miotPowerState(const String & state)
{
    BLINKER_LOG("need set power state: ", state);

    if (state == BLINKER_CMD_ON) {
        digitalWrite(LED_BUILTIN, HIGH);

        BlinkerMIOT.powerState("on");
        BlinkerMIOT.print();

        oState = true;
    }
    else if (state == BLINKER_CMD_OFF) {
        digitalWrite(LED_BUILTIN, LOW);

        BlinkerMIOT.powerState("off");
        BlinkerMIOT.print();

        oState = false;
    }
}

void miotQuery(int32_t queryCode)
{
    BLINKER_LOG("MIOT Query codes: ", queryCode);

    switch (queryCode)
    {
        case BLINKER_CMD_QUERY_ALL_NUMBER :
            BLINKER_LOG("MIOT Query All");
            BlinkerMIOT.powerState(oState ? "on" : "off");
            BlinkerMIOT.print();
            break;
        case BLINKER_CMD_QUERY_POWERSTATE_NUMBER :
            BLINKER_LOG("MIOT Query Power State");
            BlinkerMIOT.powerState(oState ? "on" : "off");
            BlinkerMIOT.print();
            break;
        default :
            BlinkerMIOT.powerState(oState ? "on" : "off");
            BlinkerMIOT.print();
            break;
    }
}

void dataRead(const String & data)
{
    BLINKER_LOG("Blinker readString: ", data);

    Blinker.vibrate();
    
    uint32_t BlinkerTime = millis();
    
    Blinker.print("millis", BlinkerTime);
}

void setup()
{
    Serial.begin(115200);
    BLINKER_DEBUG.stream(Serial);

    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, LOW);

    Blinker.begin(auth, ssid, pswd);
    Blinker.attachData(dataRead);
    
    BlinkerMIOT.attachPowerState(miotPowerState);
    BlinkerMIOT.attachQuery(miotQuery);
}

void loop()
{
    Blinker.run();
    BlinkerMIOT.run();
}

```
## 编译信息
In file included from C:\Users\ybyllc\Documents\Arduino\libraries\blinker-library-dev_4.0\src/BlinkerWiFi.h:7,
                 from C:\Users\ybyllc\Documents\Arduino\libraries\blinker-library-dev_4.0\src/Blinker.h:11,
                 from C:\Users\ybyllc\AppData\Local\Temp\arduino_modified_sketch_292735\MIOT_OUTLET.ino:50:
C:\Users\ybyllc\Documents\Arduino\libraries\blinker-library-dev_4.0\src/Blinker/BlinkerProtocol.h: In member function 'void BlinkerProtocol<Transp>::begin()':
C:\Users\ybyllc\Documents\Arduino\libraries\blinker-library-dev_4.0\src/Blinker/BlinkerProtocol.h:261:64: error: 'class EspClass' has no member named 'getCoreVersion'; did you mean 'getSdkVersion'?
     BLINKER_LOG(TAG_PROTO, BLINKER_F("package version: "), ESP.getCoreVersion());
                                                                ^~~~~~~~~~~~~~
                                                                getSdkVersion

**Comment by coloz** [comment]
请使用最新的dev4.0配合esp32 package 2.0.5测试
