### ISSUE TITLE
blinker天气api的问题

### ISSUE THREAD

**Issue by zmy2023** [blinker-iot/blinker-library#596]
## 基本信息
- [] 这个问题满足提问指南
- [] 我阅读了开发文档
- [] 我使用了最新的库及APP进行测试，但是问题仍然存在
- [] 我搜索过类似问题的解决方法但是仍然无法解决
- [] 有设备端的LOG信息
- [] 有编译报错信息
- [] 我已填写基本信息

## 设备信息
wifiduino
## IDE 中的设置
全是一步步来的，找了好几个教程，也看了店家的设置，都一样
## 手机信息及APP信息
跟这个没关系，我用chrome访问也报错

## 问题描述
blinker天气api返回{"message":1509,"detail":""}，有时候返回网络错误，而且访问次数没满，

**Comment by coloz** [comment]
是测试的自带的例程吗？哪个例程呢？
