### ISSUE TITLE
Arduino编译有大量警告，因为不符合iso C++标准

### ISSUE THREAD

**Issue by flywhc** [blinker-iot/blinker-library#598]
## 问题描述
使用Arduino 1.8.19编译Hello Wifi有大量警告，很多甚至是blinker-library内部代码的警告
经查看这里的源码发现是因为错误声明导致的。
例如 
`class BlinkerButton:: BlinkerButton(char _name[], blinker_callback_with_string_arg_t _func = NULL)`

这里不应该使用数组char _name[] 而是应该使用const char * _name，才能方便调用者传入各种类型字符串。
因为在C/C++语法里把常量字符串强制转换成字符数组是一种不安全操作。

还有错误使用register关键字，见后面编译提示。

## 代码
见官方范例 Hello WiFi

## 编译信息
```
d:\Documents\Arduino\libraries\Blinker\src/Blinker/BlinkerApiBase.h:196:29: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  196 |                 else return "false";
      |                             ^~~~~~~
\Blinker\examples\Blinker_Hello\Hello_WiFi\Hello_WiFi.ino:55:23: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   55 | BlinkerButton Button1("btn-abc");
arduino\libraries\blinker\src\modules\taskscheduler\taskscheduler.h:872:28: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  872 |     register unsigned long m, i;  // millis, interval;
```

**Comment by coloz** [comment]
一个编程的基本常识：warning不是报错，通常都可以忽略，几乎您使用任何库都会有warning

**Comment by sherlocknieh** [comment]
可以修改编译参数屏蔽警告. 如果在用 PlatformIO IDE, 可以在 platformio.ini 里添加:

build_unflags = -Wwrite-strings
build_flags = -Wno-write-strings

第一行取消 write-strings 警告, 第二行强制关闭 write-strings 警告
