### ISSUE TITLE
关于ESP8266 代码一点小问题

### ISSUE THREAD

**Issue by zlw235789** [blinker-iot/blinker-library#608]
www.arduino.cn 无法访问，不能去哪里提问抱歉

 1. Blinker.begin(auth, ssid, pswd);  可以去掉后面的参数ssid ，pswd吗，或者添加一个重构函数，我想自己建立并管理wifi连接。
 2. Blinker不用全局变量，改成实例变量 Blinker b=Blinker (auth); 可以吗
 3. 能加个mqtt 小度 语音示例吗  ardunio: void setup() loop(), 
 4. 谢谢

**Comment by coloz** [comment]
1. https://diandeng.tech/doc/config-tool?keyword=%E9%85%8D%E7%BD%91
2. 暂无该计划
3. examples中有示例
